# @package _global_
training:
  seed: 0
  checkpoint_dir: ./checkpoint/vkitti
  save_freq: 2000
  log_dir: ./logs/vkitti
  freeze_mode: default
  grad_accum: 1

optimizer:
  kind: adamw
  learning_rate: 1.0e-4
  dec_lr: 1.0e-4
  other_lr: 1.0e-4
  lora_lr: 1.0e-4
  weight_decay: 0.01

dataset:
  train:
    mode: train
    data_dirs: ['${oc.env:VKITTI_ROOT,/mnt/workspace/vkitti/vkitti}']
    crop_size: 448
    seq_len: 4
  val:
    mode: val
    data_dirs: ['${oc.env:VKITTI_ROOT,/mnt/workspace/vkitti/vkitti}']
    crop_size: 448
    seq_len: 4

dataloader:
  batch_size: 8
  num_workers: 8

model:
  video_path: null
  backbone: DINOv3ConvNeXtSmallBackbone
  backbone_weights: null
  require_pretrained_backbone: true
  encoder_decoder_only: true
  decoder: DPTHeadMultiScaleRefineConvNeXt
  use_gem: false
  use_astt: false
  use_temporal: true
  lora: true
  lora_r: 8
  lora_alpha: 16
  lora_dropout: 0.0
  multiscale_native_res: true
  multiscale_fullres_mode: none
  multiscale_depth_feedback: true
  multiscale_fp32_head: true

encoder: vitl
pose_flag: false
multiscale_loss: video
num_gpus: 1
total_step: 20000
project_name: vkitti
resume: false
